name: Patch and Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
          echo "Compile_Date=$(date +%H%M%d%m%Y)" >> $GITHUB_ENV

      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
   
      - name: Build
        run: ./gradlew createReobfPaperclipJar --stacktrace
           
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: "1.20.1 build ${{ env.Compile_Date }}"
          body: |
            Foldenor build
            Version: 1.20.1
            Build Time: ${{ env.Compile_Date }}
          tag_name: "latest-1.20.1 ${{ env.Compile_Date }}"
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
