name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyPatches
        
      - name: Build
        run: ./gradlew createReobfBundlerJar
        
      - name: Make release zip
        run: |
          7z a -tzip "core.zip" "build/libs/*"
          
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest build from action with id ${{github.run_number}}
          tag_name: Actions_Build_${{github.run_number}}
          files: core.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
