name: Patch and Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
    runs-on: ubuntu-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checking Environment
        run: |
          echo "Compile_Date=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      
      #- name: Validate Gradle wrapper
        #uses: gradle/wrapper-validation-action@v1
      
      #- name: Setup Gradle
        #uses: gradle/gradle-build-action@v2
        #with:
          #gradle-version: current
      
      #- name: Set up JDK
        #uses: actions/setup-java@v3
        #with:
          #distribution: 'temurin'
          #java-version: '17'
          
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
      
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
        
      - name: Build
        run: ./gradlew jar createReobfPaperclipJar --stacktrace
          
      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: Latest build from action with id ${{github.run_number}}
          body: |
            Foldenor build
            Version: 1.20.1
            Build Time: ${{ env.Compile_Date }}
          tag_name: 1.20.1_Actions_Build_${{github.run_number}}
          files: build/libs/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
