name: Patch and Build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
       contents: write
       actions: write
       
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
        
      - name: Set up JDK
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          cache: 'gradle'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: 'latest'
        
      - name: Configure Git User Details
        run: |
          git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
          echo "Compile_Date=$(date +%H:%M %d.%m.%Y)" >> $GITHUB_ENV

      - name: Apply Patches
        run: ./gradlew applyPatches --stacktrace
   
      - name: Build
        run: ./gradlew createReobfPaperclipJar --stacktrace
           
      - name: Make release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: false
          title: "1.20.1 build ${{ env.Compile_Date }}"
          automatic_release_tag: "latest-1.20.1"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/*
